/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    documents: Document;
    'audit-logs': AuditLog;
    translations: Translation;
    categories: Category;
    campaigns: Campaign;
    pages: Page;
    'faq-items': FaqItem;
    'blog-posts': BlogPost;
    representatives: Representative;
    announcements: Announcement;
    'fee-rows': FeeRow;
    'limit-tables': LimitTable;
    'nav-links': NavLink;
    'legal-pages': LegalPage;
    'cookie-rows': CookieRow;
    'page-meta': PageMeta;
    feedback: Feedback;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    translations: TranslationsSelect<false> | TranslationsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    campaigns: CampaignsSelect<false> | CampaignsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'faq-items': FaqItemsSelect<false> | FaqItemsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    representatives: RepresentativesSelect<false> | RepresentativesSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    'fee-rows': FeeRowsSelect<false> | FeeRowsSelect<true>;
    'limit-tables': LimitTablesSelect<false> | LimitTablesSelect<true>;
    'nav-links': NavLinksSelect<false> | NavLinksSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
    'cookie-rows': CookieRowsSelect<false> | CookieRowsSelect<true>;
    'page-meta': PageMetaSelect<false> | PageMetaSelect<true>;
    feedback: FeedbackSelect<false> | FeedbackSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'contact-info': ContactInfo;
  };
  globalsSelect: {
    'contact-info': ContactInfoSelect<false> | ContactInfoSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * vodafone.local LDAP username. Assigned by LDAP — not editable here.
   */
  username?: string | null;
  /**
   * Role is requested through AccessPoint and assigned from the LDAP group — it can't be changed here. Only LDAP-active users holding one of these 4 roles can log in. Which AD group maps to which role is defined in access/roleMapping.ts.
   */
  role: 'new_vertical_maker' | 'new_vertical_checker' | 'growth_checker' | 'growth_maker';
  /**
   * Up to 2MB — stored in MinIO.
   */
  avatar?: (number | null) | Media;
  /**
   * Only meaningful for Checker roles: who to temporarily hand your approval rights to while out of office. Leave empty for no delegation.
   */
  delegateTo?: (number | null) | User;
  /**
   * After this date the delegation automatically stops counting. Leave empty for it to last until you remove it.
   */
  delegationExpiresAt?: string | null;
  /**
   * The panel opens in this language every time you log in — unlike the temporary switcher above, this one persists.
   */
  preferredLocale?: ('tr' | 'en') | null;
  lastLoginAt?: string | null;
  lastLoginIp?: string | null;
  lastLoginUserAgent?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  /**
   * If set, the account is locked after repeated failed password attempts. A New Vertical Maker can clear it right here.
   */
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Images (PNG/JPG/SVG included) up to 10MB, videos up to 100MB — larger files can go through with the sidebar checkbox.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  mediaType?: ('image' | 'video') | null;
  uploadedBy?: (number | null) | User;
  /**
   * Where this image/video is used on the site — free text, e.g.: /kampanyalar#yaz-2026
   */
  usageUrl?: string | null;
  /**
   * Extra note — the 'Used In' auto-list below only scans known fields; this one is free text.
   */
  usageNote?: string | null;
  /**
   * Files over 10MB (images) / 100MB (videos) are blocked — check this and save again to upload anyway.
   */
  sizeOverrideConfirmed?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Read-only change log — nobody can edit or delete these entries.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  userEmail: string;
  userRole?: string | null;
  action:
    | 'login'
    | 'login_failed'
    | 'logout'
    | 'create'
    | 'update'
    | 'publish'
    | 'rejected'
    | 'delete'
    | 'unlock'
    | 'locked'
    | 'role_changed'
    | 'export'
    | 'denied';
  collectionSlug?: string | null;
  documentId?: string | null;
  summary: string;
  ip?: string | null;
  userAgent?: string | null;
  /**
   * Fields that changed in this save (top-level only; nested rich text/block content is truncated).
   */
  changes?:
    | {
        field?: string | null;
        before?: string | null;
        after?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Text for the admin panel's custom components (sidebar, buttons, login screen, etc.). Don't change the 'key' value — code looks up the text by it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "translations".
 */
export interface Translation {
  id: number;
  /**
   * Component code looks up the text by this value — e.g. loginBrandPanel.headline
   */
  key: string;
  tr: string;
  en: string;
  /**
   * When checked, an editor changed this row and code-default updates will no longer overwrite it.
   */
  isCustomized?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Which flow can pick this category. Campaigns, Blog, and FAQ each have their own separate list.
   */
  scope: 'campaign' | 'blog' | 'faq';
  /**
   * Name shown on the filter tab and the campaign list. E.g.: Kart
   */
  label: string;
  /**
   * Auto-generated (from the name) — a technical reference, doesn't change after saving.
   */
  slug: string;
  /**
   * Position in the list — starts at 1, lower comes first. Leave empty to append to the end automatically.
   */
  order?: number | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns".
 */
export interface Campaign {
  id: number;
  createdBy?: (number | null) | User;
  forceLiveEdit?: boolean | null;
  reviewStatus?: ('pending' | 'rejected') | null;
  /**
   * If the Checker rejects, the reason appears here. Cleared automatically when you resave the draft.
   */
  rejectionReason?: string | null;
  rejectedAt?: string | null;
  rejectedBy?: (number | null) | User;
  /**
   * A live campaign can't be edited directly. A Maker requests, a Checker approves and unpublishes; editing opens after that.
   */
  unpublishRequest?: ('none' | 'pending') | null;
  unpublishRequestedBy?: (number | null) | User;
  unpublishRequestedAt?: string | null;
  title: string;
  slug: string;
  description: string;
  image: number | Media;
  /**
   * The detail page's body copy
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Terms of participation / campaign rules
   */
  terms?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The category this campaign belongs to (categories in the Campaigns/Blog flow). If it's not in the list, go to Categories in the sidebar and create one with 'Flow: Campaigns and Blog'.
   */
  category: number | Category;
  /**
   * An expired campaign is removed from list pages; its detail page stays reachable
   */
  campaignStatus?: ('active' | 'expired') | null;
  featured?: boolean | null;
  /**
   * Text on the campaign card's button. E.g.: Detayları Gör, Hemen Katıl
   */
  ctaLabel?: string | null;
  /**
   * Address to go to when the button is clicked. If left empty, the button goes to this campaign's own detail page (/kampanyalar/{slug}) — leaving it empty is enough for most campaigns.
   */
  ctaUrl?: string | null;
  /**
   * Title shown in Google search results and link shares. If left empty, the 'Title' field above is used.
   */
  seoTitle?: string | null;
  /**
   * Short description (1-2 sentences) shown below the title in Google search results. If left empty, the 'Description' field above is used.
   */
  seoDescription?: string | null;
  /**
   * Comma-separated keywords (e.g. mobile payment, virtual card). Note: Google hasn't used this tag for ranking since 2009 — no real SEO impact, informational only.
   */
  seoKeywords?: string | null;
  /**
   * Both are optional — if left empty, the campaign shows as ongoing.
   */
  startDate?: string | null;
  /**
   * Once this date passes, the campaign is automatically removed from list pages (its detail page stays reachable).
   */
  endDate?: string | null;
  /**
   * If checked, this campaign appears in the footer's 'Kampanyalar' column on every page of the site.
   */
  showInFooter?: boolean | null;
  /**
   * Position in the footer (1-7). Leave empty to automatically take the first open slot in 1-7. At most 7 records can show in the footer at once.
   */
  footerOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * New pages (campaign landing, hub page, etc.) — built by dragging and dropping blocks, no developer needed. First time? Click the '?' button above — the step-by-step walkthrough is there.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * The page's name — both the page's title and the source text the URL is auto-derived from.
   */
  title: string;
  /**
   * Auto-generated for the URL: /{slug}
   */
  slug: string;
  /**
   * The page is built top-to-bottom from the blocks you add below — each block is one section. Drag to reorder, use the trash icon to delete. The small image on each '+ Add Layout' card shows what that block is for; the FULL list of which block to use when is in the '?' (Help) button at the top of the page. To show this page in the header's 'Products' menu just tick 'Show in the 'Products' Menu' in the sidebar; the footer and Main Menu are still managed from the 'Nav Links' collection (explained in Help).
   */
  layout?:
    | (
        | {
            /**
             * The large, bold heading at the top of the page. Keep it short and bold. E.g.: "Vodafone'lu Ol, Ödemenin Akıllı Halini Keşfet!" · "Faturana Yansıt, Sonra Öde". Optional.
             */
            heading?: string | null;
            /**
             * The supporting line under the heading — makes the heading's promise concrete. E.g.: "Hemen Vodafone Pay'e geç, alışverişini tek dokunuşla tamamla." Optional.
             */
            subheading?: string | null;
            /**
             * The large full-width image at the top of the page. Use Vodafone brand imagery (red background + Pay logo, or an app screenshot). Recommended size: 1440x600px.
             */
            image: number | Media;
            /**
             * Text on the button. E.g.: "Hemen Başla" · "Detayları Gör" · "Uygulamayı İndir". If left empty, no button is shown.
             */
            ctaLabel?: string | null;
            /**
             * Address to go to when the button is clicked, e.g.: /kampanyalar or https://... . Must be filled if ctaLabel is filled.
             */
            ctaUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * This text section's heading. E.g.: "Vodafone Pay Nedir?" · "Neden Vodafone Pay?". If left empty, only the text shows, with no heading.
             */
            heading?: string | null;
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            /**
             * The FAQ section's heading. E.g.: "Vodafone Pay Hakkında Merak Edilenler". Optional.
             */
            heading?: string | null;
            category?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqList';
          }
        | {
            /**
             * The showcase's heading. E.g.: "Vodafone'lulara Özel Kampanyalar" · "Bu Ayın Fırsatları".
             */
            heading: string;
            category?: string | null;
            /**
             * Pick a category above first — only that category's campaigns are listable here. If you select none, ALL campaigns in the category are shown.
             */
            campaigns?: (number | Campaign)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'campaignGrid';
          }
        | {
            /**
             * The heading shown above the video. E.g.: "Vodafone Pay Nasıl Kullanılır?" · "60 Saniyede Faturana Yansıt". Optional.
             */
            heading?: string | null;
            /**
             * Just the video ID — not the full URL. Enter the ABC123XYZ part of https://www.youtube.com/watch?v=ABC123XYZ.
             */
            youtubeId: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            /**
             * The showcase's heading. E.g.: "Anlaşmalı Bankalar" · "Vodafone Pay'i Kullanabileceğiniz Yerler". Optional.
             */
            heading?: string | null;
            /**
             * Each row is one logo. Use '+ Add Logo' to add a new one, drag to reorder.
             */
            logos?:
              | {
                  /**
                   * The logo's name (not shown on screen, used for accessibility/alt text).
                   */
                  name: string;
                  /**
                   * The logo image.
                   */
                  logo: number | Media;
                  /**
                   * Address to go to when the logo is clicked. If left empty, the logo isn't clickable.
                   */
                  linkUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logoGrid';
          }
        | {
            /**
             * The section's heading. E.g.: "Vodafone Pay Ayrıcalıkları" · "Akıllı Ödeme Yöntemleri". Optional.
             */
            heading?: string | null;
            /**
             * The paragraph under the heading. Optional.
             */
            description?: string | null;
            /**
             * Each row is one card (icon + title + short text). Use '+ Add Card' to add a new one, drag to reorder. Usually 3 cards are used.
             */
            cards?:
              | {
                  /**
                   * A small icon image — from the Vodafone icon set, preferably a single color (red or dark grey), 64x64px.
                   */
                  icon: number | Media;
                  /**
                   * The card's title — 2-4 words. E.g.: "Size Özel Limit" · "Anında Bakiye" · "Temassız Öde".
                   */
                  title: string;
                  /**
                   * The card's short text, 1-2 sentences. E.g.: "Faturana yansıt, ay sonunda tek seferde öde. Ekstra ücret yok."
                   */
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'iconCards';
          }
        | {
            /**
             * The section's heading. E.g.: "3 Adımda Vodafone Pay" · "Nasıl Kullanırım?". Optional.
             */
            heading?: string | null;
            /**
             * Each row is one step (number + text + an image showing that step). Use '+ Add Step' to add a new one, drag to reorder.
             */
            steps?:
              | {
                  /**
                   * The step number, e.g.: '01', '02'.
                   */
                  number: string;
                  /**
                   * Text describing what the user does at this step.
                   */
                  text: string;
                  /**
                   * A screenshot/image showing this step.
                   */
                  image: number | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'steps';
          }
        | {
            /**
             * The section's heading. E.g.: "Vodafone Pay ile Nasıl Kazanırım?".
             */
            heading: string;
            /**
             * The large product image shown on the right (on top on mobile) — usually a phone screenshot. Recommended width: 350px.
             */
            image: number | Media;
            /**
             * The steps listed beside the image (icon + title + description), joined by a connector line. Usually 3 steps.
             */
            steps?:
              | {
                  /**
                   * The step's icon (72x72px recommended).
                   */
                  icon: number | Media;
                  /**
                   * The step's title, e.g.: 'Bakiye Yükle'.
                   */
                  title: string;
                  /**
                   * A short description of the step.
                   */
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'howToEarn';
          }
        | {
            /**
             * The heading shown beside the image. E.g.: "Nereden satın alabilirim?" · "Nerelerde kullanabilirim?".
             */
            heading: string;
            /**
             * The explanatory copy under the heading — 2-4 sentences.
             */
            text: string;
            /**
             * The illustration shown alongside. Recommended width: 434px.
             */
            image: number | Media;
            /**
             * Which side the image sits on for desktop. On mobile the image is always shown first.
             */
            imageSide?: ('left' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageWithText';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricesAndLimits';
          }
        | {
            /**
             * The showcase's heading. E.g.: "Bloglar" · "Son Yazılar".
             */
            heading: string;
            category?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'blogGrid';
          }
        | {
            /**
             * The section's heading. E.g.: "Vodafone Pay'in Ayrıcalıklı Dünyası". Optional.
             */
            heading?: string | null;
            /**
             * The large image on the right (desktop only). If this is set, the video below is ignored.
             */
            media?: (number | null) | Media;
            /**
             * The video that loops on the right (desktop only, muted, autoplays). Only used when the image above is empty.
             */
            video?: (number | null) | Media;
            /**
             * The features listed down the left (icon + title + short copy). Usually 3-4 of them.
             */
            features?:
              | {
                  /**
                   * The feature's icon (36x36px recommended).
                   */
                  icon: number | Media;
                  /**
                   * The feature's title, e.g.: 'Akıllı Ödeme Yöntemleri'.
                   */
                  title: string;
                  /**
                   * A one-sentence description of the feature.
                   */
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureHighlights';
          }
        | {
            /**
             * The section's heading. E.g.: "Yönetim Kurulu ve Üst Yönetim" · "Ekibimiz". Optional.
             */
            heading?: string | null;
            /**
             * Each row is one person (photo + name + role). Lays out 3 across on desktop, 2 on tablet, 1 on mobile.
             */
            people?:
              | {
                  /**
                   * The person's photo. Recommended size: 291x200px.
                   */
                  photo: number | Media;
                  /**
                   * Full name.
                   */
                  name: string;
                  /**
                   * Role, e.g.: 'Genel Müdür'.
                   */
                  title: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'profileGrid';
          }
        | {
            /**
             * The section's centred heading. Leave empty to use the homepage's own.
             */
            heading?: string | null;
            /**
             * The intro copy under the heading. Optional.
             */
            description?: string | null;
            /**
             * Each row is one product showcase (phone image + title + copy). The image always sits on the same side, in a consistent layout.
             */
            steps?:
              | {
                  /**
                   * The phone screenshot. Recommended width: 560px.
                   */
                  image: number | Media;
                  /**
                   * The product name, e.g. 'Faturana Yansıt'.
                   */
                  title: string;
                  /**
                   * A short description of the product.
                   */
                  description: string;
                  /**
                   * The label of the link button under the step. If ctaPage is empty, no button is shown.
                   */
                  ctaLabel?: string | null;
                  /**
                   * The page the button links to — pickable only from published, public pages.
                   */
                  ctaPage?: (number | null) | Page;
                  /**
                   * A decorative image that sits behind/under the text (e.g. the Vodafone Pay logo). Must not interfere with text readability. Optional.
                   */
                  backgroundImage?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stepPhones';
          }
        | {
            /**
             * The white heading over the panel.
             */
            heading: string;
            /**
             * Copy under the heading. Optional.
             */
            text?: string | null;
            /**
             * The panel's background art — the copy sits ON it in white, so pick a dark image. Recommended: 1030x420px.
             */
            backgroundImage: number | Media;
            /**
             * YouTube ID (not the full URL) of a video to embed inside the panel. Leave empty for no video.
             */
            youtubeId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaPanel';
          }
        | {
            /**
             * The section heading, e.g. 'İletişim Bilgileri'. Optional.
             */
            heading?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactInfo';
          }
        | {
            /**
             * The section heading. Optional.
             */
            heading?: string | null;
            /**
             * How many representatives to show at most. Leave empty for ALL — for the full directory the /temsilciliklerimiz page is usually the better place.
             */
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'representatives';
          }
        | {
            /**
             * The section's heading, e.g.: 'Neler Kazanırsın?'. Optional.
             */
            heading?: string | null;
            /**
             * The paragraph under the heading. Optional.
             */
            intro?: string | null;
            /**
             * If set, the slides render as a carousel showing ONE slide at a time next to this fixed image (dot navigation) — leave empty to keep the slides as a horizontal scrolling strip.
             */
            sideImage?: (number | null) | Media;
            /**
             * Each row is one slide (image + text). Use '+ Add Slide' to add a new one, drag to reorder.
             */
            slides?:
              | {
                  /**
                   * The slide's image.
                   */
                  image: number | Media;
                  /**
                   * The slide's text.
                   */
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageTextSlides';
          }
        | {
            /**
             * The section's heading. Optional.
             */
            heading?: string | null;
            /**
             * A second line under the heading. Only shown while 'Dark Background Image' is set. Optional.
             */
            subheading?: string | null;
            /**
             * If set, the section renders as a dark panel with this image as a full-width background (heading/subheading/video labels in white) — leave empty to keep the videos as a light card grid.
             */
            darkBackgroundImage?: (number | null) | Media;
            /**
             * Each row is one video (tab title + video). Can also be used for a single video; if more than one is added, it shows as tabs.
             */
            videos?:
              | {
                  /**
                   * This video's tab/title text, e.g.: 'Nasıl Kart Alırım?'.
                   */
                  title: string;
                  /**
                   * Just the video ID — not the full URL. Enter the ABC123XYZ part of https://www.youtube.com/watch?v=ABC123XYZ.
                   */
                  youtubeId: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'videoList';
          }
        | {
            /**
             * Each row is one tab (the pill at the top) plus the cards shown under it. Leave empty and the block renders nothing.
             */
            tabs?:
              | {
                  /**
                   * Text on the tab button. E.g.: "Faturana Yansıt'ı alışverişte nasıl kullanırım?".
                   */
                  label: string;
                  items?:
                    | {
                        /**
                         * The text under the card, e.g.: "Google Play".
                         */
                        label: string;
                        /**
                         * The image inside the card — usually a still from the video. If empty, a plain play icon is shown instead. Recommended size: 180x280px.
                         */
                        thumbnail?: (number | null) | Media;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'videosWithTabsMarker';
          }
        | {
            /**
             * The banner's background — usually the red Vodafone Pay artwork. If empty, the default banner image is used. Recommended size: 1030x160px.
             */
            backgroundImage?: (number | null) | Media;
            /**
             * The small icon to the left of the text (64x64px recommended). If empty, the default icon is used.
             */
            icon?: (number | null) | Media;
            /**
             * The banner's call-to-action text. If empty, the default text is used.
             */
            text?: string | null;
            /**
             * The text on the button. Defaults to "Formu doldurun" if empty.
             */
            ctaLabel?: string | null;
            /**
             * Where the button goes, e.g.: /iletisim or https://... . If empty, the button isn't clickable.
             */
            ctaUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'leadFormCta';
          }
      )[]
    | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  /**
   * Comma-separated keywords (e.g. mobile payment, virtual card). Note: Google hasn't used this tag for ranking since 2009 — no real SEO impact, informational only.
   */
  seoKeywords?: string | null;
  ogImage?: (number | null) | Media;
  /**
   * Only affects the breadcrumb trail (Home > Parent > This page) — the URL stays flat at /{slug}. This list only shows OTHER Pages you've already created and saved — it's empty for your very first page, that's expected, not a bug. Example: create and save a page called 'Kurumsal' first, then create a second page 'Ekibimiz' and pick 'Kurumsal' here.
   */
  parent?: (number | null) | Page;
  /**
   * A private page is never served to visitors even when published, and is excluded from the sitemap/static build — only logged-in CMS users or the preview link can see it.
   */
  visibility?: ('public' | 'private') | null;
  /**
   * Check this and the page is automatically listed in the header's 'Products' dropdown — no separate Nav Links record needed. It only appears once the page is PUBLISHED and its Visibility is 'Public'.
   */
  showInProductsMenu?: boolean | null;
  /**
   * Leave empty to use the page's Title. Fill this in only if the menu should show shorter/different text (e.g. title 'Vodafone Pay Kart Nedir?' but menu 'Vodafone Pay Kart').
   */
  productsMenuLabel?: string | null;
  /**
   * Position in the 'Products' menu — starts at 1, lower shows higher up. Leave empty to append to the end. If the menu also has Nav Links records, both sources are sorted together in one list by this number.
   */
  productsMenuOrder?: number | null;
  createdBy?: (number | null) | User;
  /**
   * Optional — if set, shown at the very bottom of the page (just above the footer) as an 'İlgili bağlantı →' link.
   */
  deeplink?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items".
 */
export interface FaqItem {
  id: number;
  question: string;
  answer: string;
  /**
   * Optional — a related page link shown below the answer, e.g. /vodafone-pay-kart
   */
  deeplink?: string | null;
  /**
   * Determines which product page and /sikca-sorulan-sorular tab this question shows on (categories in the FAQ flow). If it's not in the list, go to Categories and create one with 'Flow: FAQ'.
   */
  category: number | Category;
  /**
   * Position in the list — starts at 1, lower comes first. Leave empty to append to the end automatically.
   */
  order?: number | null;
  /**
   * If checked, this question appears in the footer's 'Sık Sorulanlar' column on every page of the site.
   */
  showInFooter?: boolean | null;
  /**
   * Position in the footer (1-7). Leave empty to automatically take the first open slot in 1-7. At most 7 records can show in the footer at once.
   */
  footerOrder?: number | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * Auto-generated for the URL: /blog/{slug}
   */
  slug: string;
  /**
   * Cropped to 361x240 (landscape) on the list card — prefer a landscape photo over a square one.
   */
  coverImage: number | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Determines the filter tab on the blog list (categories in the Blog flow). If it's not in the list, go to Categories and create one with 'Flow: Blog'.
   */
  category: number | Category;
  /**
   * Text on the blog card's button. E.g.: Detayları Gör, Yazıyı Oku
   */
  ctaLabel?: string | null;
  publishedDate?: string | null;
  /**
   * An archived post is removed from the list page; its detail page stays reachable
   */
  postStatus?: ('active' | 'archived') | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  /**
   * Comma-separated keywords (e.g. mobile payment, virtual card). Note: Google hasn't used this tag for ranking since 2009 — no real SEO impact, informational only.
   */
  seoKeywords?: string | null;
  /**
   * Optional — a related page/campaign link shown below the post, e.g. /kampanyalar/yaz-2026
   */
  deeplink?: string | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Representative/dealer records — the /temsilciliklerimiz search form and the /temsilci/[id] detail page use this data.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "representatives".
 */
export interface Representative {
  id: number;
  businessName: string;
  /**
   * Representative code, e.g. 835343KGSM
   */
  repCode?: string | null;
  activityDescription?: string | null;
  phone?: string | null;
  mersisNo?: string | null;
  address: string;
  province: string;
  district: string;
  authorizedPerson?: string | null;
  qrCode?: (number | null) | Media;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  /**
   * E.g.: 18.08.2026 02:00-08:00 Vodafone Pay Planned Infrastructure Maintenance
   */
  title: string;
  /**
   * Leave a blank line between paragraphs.
   */
  body: string;
  /**
   * E.g.: /kampanyalar/{slug} or an app deeplink — if set, the announcement becomes clickable.
   */
  deeplink?: string | null;
  /**
   * Position in the list — starts at 1, lower comes first. Leave empty to append to the end automatically.
   */
  order?: number | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fee-rows".
 */
export interface FeeRow {
  id: number;
  label: string;
  value: string;
  /**
   * Position in the list — starts at 1, lower comes first. Leave empty to append to the end automatically.
   */
  order?: number | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "limit-tables".
 */
export interface LimitTable {
  id: number;
  title: string;
  /**
   * Position in the list — starts at 1, lower comes first. Leave empty to append to the end automatically.
   */
  order?: number | null;
  rows: {
    category: string;
    period: string;
    unverifiedLimit: string;
    verifiedLimit: string;
    id?: string | null;
  }[];
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav-links".
 */
export interface NavLink {
  id: number;
  /**
   * Text shown in the menu/footer, e.g.: 'Vodafone Pay Kart'.
   */
  label: string;
  /**
   * Address to go to when clicked. For an internal page start with / (e.g. /vodafone-pay-kart, or /{that page's slug} for a page you created in Pages); for an external link start with https:// (e.g. the Bilgi Toplum Hizmetleri link). This field accepts ANY address — a developer can give you the list of the site's existing page addresses.
   */
  href: string;
  /**
   * If left empty, mobile uses the same address (href) as above. Fill this in only if mobile devices should go somewhere DIFFERENT (e.g. an app deeplink).
   */
  mobileHref?: string | null;
  /**
   * WHERE will this link appear? Header — Ürünler = the 'Ürünler' dropdown in the top menu. Header — Ana Menü = the rest of the top menu (Kampanyalar, Blog, etc.). Footer — Kurumsal/Yasal correspond to those two footer columns, and each one holds at most 7 links (so the footer doesn't overflow) — to add another to a full column, delete an existing one first. The footer's 'Sık Sorulanlar' and 'Kampanyalar' columns are no longer managed HERE — use the 'Show in Footer' checkbox on the relevant FAQ/Campaign record instead (same 7 limit applies there too). To REMOVE a link, delete this record; to reorder, use the drag-and-drop tool on the list.
   */
  section: 'header-products' | 'header-main' | 'footer-kurumsal' | 'footer-yasal';
  /**
   * Position in the list — starts at 1, lower comes first. Leave empty to append to the end automatically.
   */
  order?: number | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Structural parts of these legal pages (tables/lists) stay fixed in code; what's managed here is intro text, plus the page image and document groups for Sözleşmeler ve Formlar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  slug:
    | 'gizlilik-ve-guvenlik-politikasi'
    | 'cerez-politikasi'
    | 'bilgi-guvenligi'
    | 'sozlesmeler-ve-formlar'
    | 'web-sitesi-hukum-ve-sartlari';
  title: string;
  intro: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Shown above the Sözleşmeler ve Formlar page's title. Optional.
   */
  heroImage?: (number | null) | Media;
  /**
   * Only for the Sözleşmeler ve Formlar page: downloadable documents, organized into labeled groups.
   */
  groups?:
    | {
        label: string;
        documents?:
          | {
              /**
               * The non-clickable part shown BEFORE the link. E.g. 'For the Consumer Rights Information Form, '. Optional — leave empty for a line that's just the link text.
               */
              prefix?: string | null;
              /**
               * The clickable part. E.g. 'click here'.
               */
              label: string;
              /**
               * Upload a PDF / Audio File: publish a signed/official document or a voiced recording as-is — e.g. an audio file for the 'Seslendirilmiş Sözleşme ve Formlar' group. Write it here: type the text and it's published as a real page on our own domain (/sozlesmeler-ve-formlar/...).
               */
              source: 'pdf' | 'page';
              /**
               * The uploaded file is stored in MinIO. On the site, clicking it takes the user straight to the file (leaving vodafonepaycomtr) — the browser's own PDF viewer/audio player takes over.
               */
              file?: (number | null) | Document;
              /**
               * Generated automatically from the document label. The page is published at /sozlesmeler-ve-formlar/{address}
               */
              slug?: string | null;
              /**
               * Write the contract/form text here. Headings, lists, tables and links are available.
               */
              body?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              enabled?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional — if set, shown as an 'İlgili bağlantı →' link at the bottom of the page.
   */
  deeplink?: string | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Rows of the cookie table on the /cerez-politikasi page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-rows".
 */
export interface CookieRow {
  id: number;
  name: string;
  provider: string;
  party: 'Birinci taraf' | 'Üçüncü taraf';
  category: 'Zorunlu' | 'İşlevsel' | 'Performans (Analitik)' | 'Reklam/Pazarlama';
  description: string;
  duration: string;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Per-page breadcrumb text and SEO fields. pageKey must exactly match the site's route (e.g.: /aninda-bakiye).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-meta".
 */
export interface PageMeta {
  id: number;
  /**
   * E.g.: /, /aninda-bakiye, /kampanyalar
   */
  pageKey: string;
  breadcrumbLabel?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  /**
   * Comma-separated keywords (e.g. mobile payment, virtual card). Note: Google hasn't used this tag for ranking since 2009 — no real SEO impact, informational only.
   */
  seoKeywords?: string | null;
  ogImage?: (number | null) | Media;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback".
 */
export interface Feedback {
  id: number;
  message: string;
  area?: string | null;
  pagePath?: string | null;
  userEmail: string;
  userRole?: string | null;
  ip?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'translations';
        value: number | Translation;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'campaigns';
        value: number | Campaign;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'faq-items';
        value: number | FaqItem;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'representatives';
        value: number | Representative;
      } | null)
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null)
    | ({
        relationTo: 'fee-rows';
        value: number | FeeRow;
      } | null)
    | ({
        relationTo: 'limit-tables';
        value: number | LimitTable;
      } | null)
    | ({
        relationTo: 'nav-links';
        value: number | NavLink;
      } | null)
    | ({
        relationTo: 'legal-pages';
        value: number | LegalPage;
      } | null)
    | ({
        relationTo: 'cookie-rows';
        value: number | CookieRow;
      } | null)
    | ({
        relationTo: 'page-meta';
        value: number | PageMeta;
      } | null)
    | ({
        relationTo: 'feedback';
        value: number | Feedback;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  username?: T;
  role?: T;
  avatar?: T;
  delegateTo?: T;
  delegationExpiresAt?: T;
  preferredLocale?: T;
  lastLoginAt?: T;
  lastLoginIp?: T;
  lastLoginUserAgent?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  mediaType?: T;
  uploadedBy?: T;
  usageUrl?: T;
  usageNote?: T;
  sizeOverrideConfirmed?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  userEmail?: T;
  userRole?: T;
  action?: T;
  collectionSlug?: T;
  documentId?: T;
  summary?: T;
  ip?: T;
  userAgent?: T;
  changes?:
    | T
    | {
        field?: T;
        before?: T;
        after?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "translations_select".
 */
export interface TranslationsSelect<T extends boolean = true> {
  key?: T;
  tr?: T;
  en?: T;
  isCustomized?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  scope?: T;
  label?: T;
  slug?: T;
  order?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns_select".
 */
export interface CampaignsSelect<T extends boolean = true> {
  createdBy?: T;
  forceLiveEdit?: T;
  reviewStatus?: T;
  rejectionReason?: T;
  rejectedAt?: T;
  rejectedBy?: T;
  unpublishRequest?: T;
  unpublishRequestedBy?: T;
  unpublishRequestedAt?: T;
  title?: T;
  slug?: T;
  description?: T;
  image?: T;
  body?: T;
  terms?: T;
  category?: T;
  campaignStatus?: T;
  featured?: T;
  ctaLabel?: T;
  ctaUrl?: T;
  seoTitle?: T;
  seoDescription?: T;
  seoKeywords?: T;
  startDate?: T;
  endDate?: T;
  showInFooter?: T;
  footerOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              image?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        faqList?:
          | T
          | {
              heading?: T;
              category?: T;
              id?: T;
              blockName?: T;
            };
        campaignGrid?:
          | T
          | {
              heading?: T;
              category?: T;
              campaigns?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              heading?: T;
              youtubeId?: T;
              id?: T;
              blockName?: T;
            };
        logoGrid?:
          | T
          | {
              heading?: T;
              logos?:
                | T
                | {
                    name?: T;
                    logo?: T;
                    linkUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        iconCards?:
          | T
          | {
              heading?: T;
              description?: T;
              cards?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        steps?:
          | T
          | {
              heading?: T;
              steps?:
                | T
                | {
                    number?: T;
                    text?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        howToEarn?:
          | T
          | {
              heading?: T;
              image?: T;
              steps?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        imageWithText?:
          | T
          | {
              heading?: T;
              text?: T;
              image?: T;
              imageSide?: T;
              id?: T;
              blockName?: T;
            };
        pricesAndLimits?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        blogGrid?:
          | T
          | {
              heading?: T;
              category?: T;
              id?: T;
              blockName?: T;
            };
        featureHighlights?:
          | T
          | {
              heading?: T;
              media?: T;
              video?: T;
              features?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        profileGrid?:
          | T
          | {
              heading?: T;
              people?:
                | T
                | {
                    photo?: T;
                    name?: T;
                    title?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stepPhones?:
          | T
          | {
              heading?: T;
              description?: T;
              steps?:
                | T
                | {
                    image?: T;
                    title?: T;
                    description?: T;
                    ctaLabel?: T;
                    ctaPage?: T;
                    backgroundImage?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        mediaPanel?:
          | T
          | {
              heading?: T;
              text?: T;
              backgroundImage?: T;
              youtubeId?: T;
              id?: T;
              blockName?: T;
            };
        contactInfo?:
          | T
          | {
              heading?: T;
              id?: T;
              blockName?: T;
            };
        representatives?:
          | T
          | {
              heading?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        imageTextSlides?:
          | T
          | {
              heading?: T;
              intro?: T;
              sideImage?: T;
              slides?:
                | T
                | {
                    image?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        videoList?:
          | T
          | {
              heading?: T;
              subheading?: T;
              darkBackgroundImage?: T;
              videos?:
                | T
                | {
                    title?: T;
                    youtubeId?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        videosWithTabsMarker?:
          | T
          | {
              tabs?:
                | T
                | {
                    label?: T;
                    items?:
                      | T
                      | {
                          label?: T;
                          thumbnail?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        leadFormCta?:
          | T
          | {
              backgroundImage?: T;
              icon?: T;
              text?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              id?: T;
              blockName?: T;
            };
      };
  seoTitle?: T;
  seoDescription?: T;
  seoKeywords?: T;
  ogImage?: T;
  parent?: T;
  visibility?: T;
  showInProductsMenu?: T;
  productsMenuLabel?: T;
  productsMenuOrder?: T;
  createdBy?: T;
  deeplink?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items_select".
 */
export interface FaqItemsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  deeplink?: T;
  category?: T;
  order?: T;
  showInFooter?: T;
  footerOrder?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  coverImage?: T;
  body?: T;
  category?: T;
  ctaLabel?: T;
  publishedDate?: T;
  postStatus?: T;
  seoTitle?: T;
  seoDescription?: T;
  seoKeywords?: T;
  deeplink?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "representatives_select".
 */
export interface RepresentativesSelect<T extends boolean = true> {
  businessName?: T;
  repCode?: T;
  activityDescription?: T;
  phone?: T;
  mersisNo?: T;
  address?: T;
  province?: T;
  district?: T;
  authorizedPerson?: T;
  qrCode?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  deeplink?: T;
  order?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fee-rows_select".
 */
export interface FeeRowsSelect<T extends boolean = true> {
  label?: T;
  value?: T;
  order?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "limit-tables_select".
 */
export interface LimitTablesSelect<T extends boolean = true> {
  title?: T;
  order?: T;
  rows?:
    | T
    | {
        category?: T;
        period?: T;
        unverifiedLimit?: T;
        verifiedLimit?: T;
        id?: T;
      };
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav-links_select".
 */
export interface NavLinksSelect<T extends boolean = true> {
  label?: T;
  href?: T;
  mobileHref?: T;
  section?: T;
  order?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  intro?: T;
  heroImage?: T;
  groups?:
    | T
    | {
        label?: T;
        documents?:
          | T
          | {
              prefix?: T;
              label?: T;
              source?: T;
              file?: T;
              slug?: T;
              body?: T;
              enabled?: T;
              id?: T;
            };
        id?: T;
      };
  deeplink?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-rows_select".
 */
export interface CookieRowsSelect<T extends boolean = true> {
  name?: T;
  provider?: T;
  party?: T;
  category?: T;
  description?: T;
  duration?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-meta_select".
 */
export interface PageMetaSelect<T extends boolean = true> {
  pageKey?: T;
  breadcrumbLabel?: T;
  seoTitle?: T;
  seoDescription?: T;
  seoKeywords?: T;
  ogImage?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback_select".
 */
export interface FeedbackSelect<T extends boolean = true> {
  message?: T;
  area?: T;
  pagePath?: T;
  userEmail?: T;
  userRole?: T;
  ip?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The official company and complaint-channel details shown in the footer on every page and on the Contact / Corporate Governance pages. Single record — a change here affects the whole site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info".
 */
export interface ContactInfo {
  id: number;
  /**
   * The company's official registered name — shown on the first line of the footer's legal block and on legal pages.
   */
  companyName: string;
  /**
   * Trade registry number. Legally required to appear on the site — shown in the footer's legal block.
   */
  tradeRegistryNo: string;
  /**
   * The company's registered address. Shown verbatim in the footer and on the Contact page — line breaks are preserved.
   */
  address: string;
  /**
   * The number customers call. Rendered as a click-to-call link on the Contact page.
   */
  phone: string;
  /**
   * Registered Electronic Mail address used for official/legal correspondence. Different from a normal email address, and legally required to be published.
   */
  kepAddress: string;
  /**
   * Explains how a customer can file a complaint and how quickly they'll get a reply. Shown verbatim on the Contact / Corporate Governance page.
   */
  customerServiceText: string;
  /**
   * Address of the Central Bank of Türkiye — the official body a customer escalates to if the company doesn't resolve their complaint. Legally required.
   */
  tcmbAddress: string;
  /**
   * Phone number for escalating to the Central Bank — shown in the same block as the address above.
   */
  tcmbPhone: string;
  /**
   * Central Bank fax number. Rarely used today, but still has to be published as an official channel.
   */
  tcmbFax: string;
  /**
   * The Central Bank's registered electronic mail address, for filing an official escalation electronically.
   */
  tcmbKep: string;
  /**
   * Optional — URL of Vodafone's press/media page. Fill it in and a 'Press Relations' link appears on the Contact page; leave it empty and the link isn't shown at all.
   */
  pressRelationsUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info_select".
 */
export interface ContactInfoSelect<T extends boolean = true> {
  companyName?: T;
  tradeRegistryNo?: T;
  address?: T;
  phone?: T;
  kepAddress?: T;
  customerServiceText?: T;
  tcmbAddress?: T;
  tcmbPhone?: T;
  tcmbFax?: T;
  tcmbKep?: T;
  pressRelationsUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}