apiVersion: v1
kind: Service
metadata:
  name: clover
  namespace: vepas-ai-am
  labels: { app: clover }
spec:
  type: ClusterIP
  selector: { app: clover }
  ports: [ { name: http, port: 3000, targetPort: http } ]
